[package]
name = "alluxio-common"
version = "0.1.0"
edition = "2021"

[lib]
name = "alluxio_common"
crate-type = ["lib"]
path = "src/common_lib.rs"

[dependencies]
config = "0.13.1"
serde = { version = "1.0.140", features = ["derive"] }
serde_derive = "1.0.140"
serde_json = "1.0"
